# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  profiles:
#    active: druid
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
       enabled: true
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:
    view:
      prefix: /
      suffix: .html
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    data-username: root
#    data-password: 123456
#    url: